config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  root to:'homes#top'
  get "home/about"=>"homes#about",as:"about"
  get "/search" => "searches#search"
  get "search_book" => "books#search_book"

  resources:books do
    resource:favorites,only:[:create,:destroy]
    resources:book_comments,only:[:create,:destroy]
  end

  resources:users,only:[:index,:show,:edit,:update] do
    resource:relationships,only:[:create,:destroy]
    get 'followings'=>'relationships#followings',as:'followings'
    get 'followers'=>'relationships#followers',as:'followers'
    get "search_count"=>"users#search_count"
  end

  resources :chats,only:[:show,:create]

  resources:groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord

  has_many:group_users
  has_many:users,through: :group_users

  validates:name,presence:true
  validates:introduction,presence:true
  has_one_attached:group_image

  def get_group_image
    unless group_image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      group_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    group_image.variant(resize_to_limit:[100,100]).processed
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action:authenticate_user!
  before_action:ensure_correct_user,only:[:edit,:update]

  def index
    @book=Book.new
    @groups=Group.all
  end

  def show
    @book=Book.new
    @group=Group.find(params[:id])
  end

  def join
    @group=Group.find(params[:group_id])
    @group.users << current_user
    redirect_to groups_path
  end

  def new
    @group=Group.new
  end

  def create
    @group=Group.new(group_params)
    @group.owner_id=current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render "edit"
    end
  end

  def destroy
    @group=Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  def new_mail
    @group=Group.find(params[:group_id])
  end
  
  def send_mail
    @group=Group.find(params[:group_id])
    group_users=@group.users
    @mail_title=params[:mail_title]
    @mail_content=params[:mail_content]
    ContactMailer.send_mail(@mail_title,@mail_content,group_users).deliver
  end

  private

  def group_params
    params.require(:group).permit(:name,:introduction,:group_image)
  end

  def ensure_correct_user
    @group=Group.find(params[:id])
    unless @group.owner_id==current_user.id
      redirect_to groups_path
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model:group do|f| %>
  <div class="form-group">
    <%= f.label:グループ名 %>
    <%= f.text_field:name,class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label:紹介文 %>
    <%= f.text_area:introduction,class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label:グループ画像 %><br>
    <%= f.file_field:group_image,accept:"image/*" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Group",class:"btn btn-info" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Create Group</h2>
      <%= render "groups/form",group:@group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info',user:current_user %>
      <%= render 'users/setting',user:current_user %>
      <%= render 'books/new',book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Groups</h3>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td><%= image_tag group.get_group_image,size:'50x50' %></td>
              <td><%= link_to group.name,group_path(group.id) %></td>
              <td><%= group.introduction %></td>
              <td><%= group.users.count %></td>
              <td>
                <% if group.owner_id==current_user.id %>
                  <%= link_to "Edit",edit_group_path(group.id),class:"btn btn-sm btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Create Group</h2>
      <%= render "groups/form",group:@group %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Event Mail</h2>
      <%= form_with url:group_send_mail_path(@group),method: :get do |f| %>
        <div class="form-group">
          <%= f.label:title %>
          <%= f.text_field:mail_title,class:'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label:content %>
          <%= f.text_area:mail_content,class:'form-control' %>
        </div>
        <div><%= f.submit '送信' %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h3 class="margin_top">送信が完了しました</h3>
    <div class="main_width">
      <div class="margin_top">内容は以下の通りです。</div>
      <div class="small_margin_top">
        [タイトル]<p class="font-weight-bold"><%= @mail_title %></p>
      </div>
      <div>
        [本文]<p class="font-weight-bold"><%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info',user:current_user %>
      <%= render 'users/setting',user:current_user %>
      <%= render 'books/new',book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Group Detail</h3>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_group_image,size:'50x50' %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |member| %>
                <%= member.name %><br>
              <% end %>
            </td>
            <td>
              <% if @group.owner_id==current_user.id %>
                <%= link_to "Edit",edit_group_path(@group.id),class:"btn btn-sm btn-success" %>
              <% elsif @group.users.include?(current_user) %>
                <%= link_to "Leave this group",group_path(@group),method: :delete,class:"btn btn-sm btn-danger" %>
              <% else %>
                <%= link_to "Join this group",group_join_path(@group),class:"btn btn-sm btn-success" %>
              <% end %>
            </td>
            <td>
              <% if @group.owner_id==current_user.id %>
                <%= link_to "Notice an Event",group_new_mail_path(@group),class:"btn btn-sm btn-primary" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>