config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  root to:'homes#top'
  get "home/about"=>"homes#about",as:"about"
  get "/search" => "searches#search"
  get "search_book" => "books#search_book"

  resources:books do
    resource:favorites,only:[:create,:destroy]
    resources:book_comments,only:[:create,:destroy]
  end

  resources:users,only:[:index,:show,:edit,:update] do
    resource:relationships,only:[:create,:destroy]
    get 'followings'=>'relationships#followings',as:'followings'
    get 'followers'=>'relationships#followers',as:'followers'
    get "search_count"=>"users#search_count"
  end

  resources :chats,only:[:show,:create]

  resources:groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:books
  has_many:favorites
  has_many:book_comments
  has_many:user_rooms
  has_many:chats
  has_many:rooms,through: :user_rooms
  has_many:view_counts

  has_many:group_users
  has_many:groups,through: :group_users

  has_many:relationships,class_name:"Relationship",foreign_key:"follower_id",dependent: :destroy
  has_many:followings,through: :relationships,source: :followed

  has_many:reverse_relationships,class_name:"Relationship",foreign_key:"followed_id",dependent: :destroy
  has_many:followers,through: :reverse_relationships,source: :follower


  has_one_attached:profile_image

  validates:name,{presence:true,uniqueness:true,length:{minimum:2,maximum:20}}
  validates:introduction,length:{maximum:50}

  def get_profile_image
    unless profile_image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[100,100]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content,method)
    if method=="perfect"
      User.where(name:content)
    elsif method=="forward"
      User.where('name LIKE?',content+'%')
    elsif method=="backward"
      User.where('name LIKE?','%'+content)
    else
      User.where('name LIKE?','%'+content+'%')
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action:is_matching_login_user,only:[:edit,:update]

  def index
    @users=User.all
    @book=Book.new
  end

  def show
    @user=User.find(params[:id])
    @books=@user.books
    @book=Book.new
    @today_book=@books.created_today
    @yesterday_book=@books.created_yesterday
    @two_days_ago_book=@books.created_two_days_ago
    @three_days_ago_book=@books.created_three_days_ago
    @four_days_ago_book=@books.created_four_days_ago
    @five_days_ago_book=@books.created_five_days_ago
    @six_days_ago_book=@books.created_six_days_ago
    @this_week_book=@books.created_this_week
    @last_week_book=@books.created_last_week
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def search_count
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "年/月/日"#①
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count#②
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  def is_matching_login_user
    user=User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image%>
<table class="table">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count,user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count,user_followers_path(user) %></th>
  </tr>
</table>

app/views/users/_search.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/_search_form.html.erb
<%= form_with url: user_search_count_path(user), method: :get,local:false do |f| %>
  <%= f.date_field :created_at %>
  <%= f.submit '検索', class: 'btn btn-primary'  %>
<% end %>

app/views/users/_setting.html.erb
<div class="row">
  <% if user==current_user %>
    <%= link_to edit_user_path(user.id),class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す",user_relationships_path(user.id),method: :delete,class:"btn btn-md btn-info" %>
    <% else %>
      <%= link_to "フォローする",user_relationships_path(user.id),method: :post,class:"btn btn-md btn-success" %>
    <% end %>
  <% end %>
  <% if current_user!=user&&current_user.following?(user)&&user.following?(current_user) %>
    <%= link_to "chatを始める",chat_path(user.id),class:"ml-3" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0">
      <h2>User info</h2>
      <%= render 'layouts/error',error:@user %>
      <%= form_with model:@user do |f| %>
        <div class="form-group">
          <label for="imputName">Name</label>
          <%= f.text_field:name,class:"form-control" %>
        </div>
        <div class="form-group">
          <label for="imputImage">Image</label><br>
          <%= f.file_field:profile_image,accept:"image/*" %>
        </div>
        <div class="form-group">
          <label for="imputIntroduction">Introduction</label>
          <%= f.text_area:introduction,class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User",class:"btn btn-md btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info',user:current_user %>
      <%= render 'users/setting',user:current_user %>
      <%= render 'books/new',book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <div><%= link_to "グループを作成する",new_group_path %> | <%= link_to "グループ一覧",groups_path %></div>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image %></td>
              <td><%= user.name %></td>
              <td>フォロー数: <%= user.followings.count %></td>
              <td>フォロワー数: <%= user.followers.count %></td>
              <td>
                <% unless current_user == user %>
                  <% if current_user.following?(user) %>
                    <%= link_to "フォロー外す",user_relationships_path(user.id),method: :delete %>
                  <% else %>
                    <%= link_to "フォローする",user_relationships_path(user.id),method: :post %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to "Show",user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/search_count.js.erb
$('#search_result').html('<%= j(render 'users/search', search_book: @search_book ) %>');

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info',user:@user %>
      <%= render 'users/setting',user:@user %>
      <%= render 'books/new',book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Tag</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= image_tag @user.get_profile_image %>
                <% end %>
              </td>
              <td><%= link_to book.title,book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td><%= link_to book.tag,search_book_path(keyword: book.tag) %></td>
              <td id="favorite-btn<%= book.id %>">
                <%= render 'favorites/favorite',book:book %>
              </td>
              <td>コメント数<%= book.book_comments.count %></td>
              <td><%= render "books/star-rate",book:book %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <h2>投稿数の前日比・前週比</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @today_book.count %></td>
            <td><%= @yesterday_book.count %></td>
            <td>
              <% if @yesterday_book.count==0 %>
                前日の投稿はありません
              <% else %>
                <% @the_day_before=@today_book.count/@yesterday_book.count.to_f %>
                <%= (@the_day_before*100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @this_week_book.count %></td>
            <td><%= @last_week_book.count %></td>
            <td>
              <% if @last_week_book.count==0 %>
                前週の投稿はありません
              <% else %>
                <% @the_week_before=@this_week_book.count/@last_week_book.count.to_f %>
                <%= (@the_week_before*100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <h2>7日間分の投稿数</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>6日前</th>
            <th>5日前</th>
            <th>4日前</th>
            <th>3日前</th>
            <th>2日前</th>
            <th>1日前</th>
            <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @six_days_ago_book.count %></td>
            <td><%= @five_days_ago_book.count %></td>
            <td><%= @four_days_ago_book.count %></td>
            <td><%= @three_days_ago_book.count %></td>
            <td><%= @two_days_ago_book.count %></td>
            <td><%= @yesterday_book.count %></td>
            <td><%= @today_book.count %></td>
          </tr>
        </tbody>
      </table>
      <canvas id="myChart"></canvas>
      <script>
        const ctx=document.getElementById('myChart').getContext('2d');
        const myChart=new Chart(ctx,{
          type:'line',
          data:{
            labels:['6日前','5日前','4日前','3日前','2日前','1日前','今日',],
            datasets:[{
              label:'投稿した本の数',
              data:[<%= @six_days_ago_book.count %>,<%= @five_days_ago_book.count %>,<%= @four_days_ago_book.count %>,<%= @three_days_ago_book.count %>,<%= @two_days_ago_book.count %>,<%= @yesterday_book.count %>,<%= @today_book.count %>],
              borderColor:'rgb(0,51,255)',
              fill:false,
              tension: 0.3
            }]
          },
          options: {
               y: {
            min: 0,
            max: 10,
            },
          },
        });
      </script>
      <div>
        <%= render 'users/search_form',user:@user %>
      </div>
      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'users/search', search_book: @search_book %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>