config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  root to:'homes#top'
  get "home/about"=>"homes#about",as:"about"
  get "/search" => "searches#search"
  get "search_book" => "books#search_book"

  resources:books do
    resource:favorites,only:[:create,:destroy]
    resources:book_comments,only:[:create,:destroy]
  end

  resources:users,only:[:index,:show,:edit,:update] do
    resource:relationships,only:[:create,:destroy]
    get 'followings'=>'relationships#followings',as:'followings'
    get 'followers'=>'relationships#followers',as:'followers'
    get "search_count"=>"users#search_count"
  end

  resources :chats,only:[:show,:create]

  resources:groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to:user

  has_many:favorites
  has_many :favorited_users, through: :favorites, source: :user
  has_many:book_comments
  has_many:view_counts
  has_many:book_tags,dependent: :destroy
  has_many:tags,through: :book_tags

  validates:title,presence:true
  validates:body,{presence:true,length:{maximum:200}}

  def favorited_by?(user)
    favorites.exists?(user_id:user.id)
  end

  def self.search(search_word)
    Book.where(['tag LIKE?',"#{search_word}"])
  end

  def self.search_for(content,method)
    if method=="perfect"
      Book.where(title:content)
    elsif method=="forward"
      Book.where('title LIKE?',content+'%')
    elsif method=="backward"
      Book.where('title LIKE?','%'+content)
    else
      Book.where('title LIKE?','%'+content+'%')
    end
  end

  scope:latest,->{order(created_at: :desc)}
  scope:old,->{order(created_at: :asc)}
  scope:star_count,->{order(star: :desc)}

  scope:created_today,->{where(created_at:Time.zone.now.all_day)}
  scope:created_yesterday,->{where(created_at:1.day.ago.all_day)}
  scope:created_two_days_ago,->{where(created_at:2.days.ago.all_day)}
  scope:created_three_days_ago,->{where(created_at:3.days.ago.all_day)}
  scope:created_four_days_ago,->{where(created_at:4.days.ago.all_day)}
  scope:created_five_days_ago,->{where(created_at:5.days.ago.all_day)}
  scope:created_six_days_ago,->{where(created_at:6.days.ago.all_day)}
  scope:created_this_week,->{where(created_at:Time.current.all_week)}
  scope:created_last_week,->{where(created_at:Time.current.last_week.all_week)}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action:is_matching_login_user,only:[:edit,:update]

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:notice]="You have created book successfully"
      redirect_to book_path(@book.id)
    else
      @books=Book.all
      render :index
    end
  end

  def index
    if params[:latest]
      @books=Book.latest
    elsif params[:old]
      @books=Book.old
    elsif params[:star_count]
      @books=Book.star_count
    else
      to=Time.current.at_end_of_day
      from=(to - 6.day).at_beginning_of_day
      @books=Book.includes(:favorited_users).
        sort{|a,b|
          b.favorited_users.includes(:favorites).where(created_at:from...to).size<=>
          a.favorited_users.includes(:favorites).where(created_at:from...to).size
        }
    end
    @book=Book.new
  end

  def show
    @book=Book.find(params[:id])
    @booknew=Book.new
    @book_comment=BookComment.new
    @user=@book.user
    @book_detail=Book.find(params[:id])
    unless ViewCount.find_by(user_id:current_user.id,book_id:@book_detail.id)
      current_user.view_counts.create(book_id:@book_detail.id)
    end
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def search_book
    @book=Book.new
    @keyword=params[:keyword]
    @books=Book.search(params[:keyword])
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:star,:tag)
  end

  def is_matching_login_user
    book=Book.find(params[:id])
    unless book.user == current_user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_new.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model:book do |f| %>
  <div class="form-group">
    <p>Title</p>
    <%= f.text_field:title,class:"form-control" %>
  </div>
  <div class="form-group">
    <p>Opinion</p>
    <%= f.text_area:body,class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "tag" %>
    <%= f.text_field:tag,class:"form-control" %>
  </div>
  <div class="form-group" id="star">
    <%= f.label "Rate" %>
    <%= f.hidden_field :star, id: :review_star %>
  </div>
  <script>
    // scriptファイルをどのidの部分に配置するかを指定
    $('#star').empty();
    let elem = document.querySelector('#star');
    let opt = {
      //星画像の指定などのオプションをここに記述,
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      scoreName: 'book[star]',
      half      : false
     };
    raty(elem,opt);
  </script>

  <div class="form-group">
    <%= f.submit "Create Book",class:"text-light btn btn-sm btn-success" %>
  </div>

<% end %>

app/views/books/_star-rate.html.erb
<div id="star-rate<%= book.id %>"></div>
<script>
   // scriptファイルをどのidの部分に配置するかを指定
  $('#star-rate<%= book.id %>').empty();
  let raty_<%= book.id %> = document.querySelector('#star-rate<%= book.id %>');
  let option_<%= book.id %> = {
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    score: "<%= book.star %>",
    readOnly: true,
  };
raty(raty_<%= book.id %> ,option_<%= book.id %>);
</script>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0">
      <h1>Editing Book</h1>
      <%= render 'layouts/error',error:@book %>
      <%= form_with model:@book do |f| %>
        <div class="form-group">
          <p>Title</p>
          <%= f.text_field:title,class:"form-control" %>
        </div>
        <div class="form-group">
          <p>Opinion</p>
          <%= f.text_area:body,class:"form-control" %>
        </div>
        <div><%= render "books/star-rate",book:@book %></div>
        <div class="form-group">
          <%= f.submit "Update Book",class:"btn btn-md btn-success" %>
        </div>
      <% end %>
      <div>
        <%= link_to "Show",book_path(@book.id) %>
        |
        <%= link_to "Back",books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/error',error:@book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info',user:current_user %>
      <%= render 'users/setting',user:current_user %>
      <%= render 'books/new',book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <p>
        <%= link_to "新しい順",books_path(latest:"true") %> |
        <%= link_to "古い順",books_path(old:"true") %> |
        <%= link_to "評価の高い順",books_path(star_count:"true") %>
      </p>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Tag</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                 <%= image_tag book.user.get_profile_image %>
                <% end %>
              </td>
              <td><%= link_to book.title,book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td><%= link_to book.tag,search_book_path(keyword: book.tag) %></td>
              <td id="favorite-btn<%= book.id %>">
                <%= render 'favorites/favorite',book:book %>
              </td>
              <td><%= l book.created_at %></td>
              <td>コメント数<%= book.book_comments.count %></td>
              <td>閲覧数:<%= book.view_counts.count %></td>
              <td><%= render "books/star-rate",book:book %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/search_book.html.erb
<h2>Books search for "<%= @keyword %>"</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= image_tag book.user.get_profile_image,size:'50x50' %></td>
      <td><%= link_to book.title,book_path(book.id) %></td>
      <td><%= book.body %></td>
      <td><%= link_to book.tag,search_book_path(keyword: book.tag) %></td>
      <td id="favorite-btn<%= book.id %>">
        <%= render 'favorites/favorite',book:book %>
      </td>
      <td>コメント数:<span id="comment_count"><%= render 'book_comments/comment_count',book:book %></span></td>
      <td><%= render "books/star-rate",book:book %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info',user:@user %>
      <%= render 'users/setting',user:@user %>
      <%= render 'books/new',book:@booknew %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
              <%= image_tag @book.user.get_profile_image %><br>
              <%= @user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title,book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <td><%= link_to @book.tag,search_book_path(keyword: @book.tag) %></td>
            <td id="favorite-btn<%= @book.id %>">
              <%= render 'favorites/favorite',book:@book %>
            </td>
          <td>コメント数:<span id="comment_count"><%= render 'book_comments/comment_count',book:@book %></span></td>
          <td>閲覧数:<%= @book_detail.view_counts.count %></td>
          <td><%= render "books/star-rate",book:@book %></td>
          <% if @book.user==current_user %>
            <td><%= link_to "Edit",edit_book_path(@book.id),class:"btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy",book_path(@book.id),method: :delete,"data-confirm"=>"本当に消しますか？",class:"btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      </table>
      <div id="book_comment_index">
        <%= render "book_comments/comment_index",book:@book %>
      </div>
      <div id="book_comment_form">
        <%= render "book_comments/comment_form",book:@book,book_comment:@book_comment %>
      </div>
    </div>
  </div>
</div>