config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  root to:'homes#top'
  get "home/about"=>"homes#about",as:"about"
  get "/search" => "searches#search"
  get "search_book" => "books#search_book"

  resources:books do
    resource:favorites,only:[:create,:destroy]
    resources:book_comments,only:[:create,:destroy]
  end

  resources:users,only:[:index,:show,:edit,:update] do
    resource:relationships,only:[:create,:destroy]
    get 'followings'=>'relationships#followings',as:'followings'
    get 'followers'=>'relationships#followers',as:'followers'
    get "search_count"=>"users#search_count"
  end

  resources :chats,only:[:show,:create]

  resources:groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to:user

  has_many:favorites
  has_many :favorited_users, through: :favorites, source: :user
  has_many:book_comments
  has_many:view_counts
  has_many:book_tags,dependent: :destroy
  has_many:tags,through: :book_tags

  validates:title,presence:true
  validates:body,{presence:true,length:{maximum:200}}

  def favorited_by?(user)
    favorites.exists?(user_id:user.id)
  end

  def self.search(search_word)
    Book.where(['tag LIKE?',"#{search_word}"])
  end

  def self.search_for(content,method)
    if method=="perfect"
      Book.where(title:content)
    elsif method=="forward"
      Book.where('title LIKE?',content+'%')
    elsif method=="backward"
      Book.where('title LIKE?','%'+content)
    else
      Book.where('title LIKE?','%'+content+'%')
    end
  end

  scope:latest,->{order(created_at: :desc)}
  scope:old,->{order(created_at: :asc)}
  scope:star_count,->{order(star: :desc)}

  scope:created_today,->{where(created_at:Time.zone.now.all_day)}
  scope:created_yesterday,->{where(created_at:1.day.ago.all_day)}
  scope:created_two_days_ago,->{where(created_at:2.days.ago.all_day)}
  scope:created_three_days_ago,->{where(created_at:3.days.ago.all_day)}
  scope:created_four_days_ago,->{where(created_at:4.days.ago.all_day)}
  scope:created_five_days_ago,->{where(created_at:5.days.ago.all_day)}
  scope:created_six_days_ago,->{where(created_at:6.days.ago.all_day)}
  scope:created_this_week,->{where(created_at:Time.current.all_week)}
  scope:created_last_week,->{where(created_at:Time.current.last_week.all_week)}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to:book
  belongs_to:user
  
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to:user
  belongs_to:room

  validates:message,presence:true,length:{maximum:140}

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to:user
  belongs_to:book

end

app/models/group.rb
class Group < ApplicationRecord

  has_many:group_users
  has_many:users,through: :group_users

  validates:name,presence:true
  validates:introduction,presence:true
  has_one_attached:group_image

  def get_group_image
    unless group_image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      group_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    group_image.variant(resize_to_limit:[100,100]).processed
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to:user
  belongs_to:group

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to:follower,class_name:"User"
  belongs_to:followed,class_name:"User"

end

app/models/room.rb
class Room < ApplicationRecord
  
  has_many:user_rooms
  has_many:chats
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:books
  has_many:favorites
  has_many:book_comments
  has_many:user_rooms
  has_many:chats
  has_many:rooms,through: :user_rooms
  has_many:view_counts

  has_many:group_users
  has_many:groups,through: :group_users

  has_many:relationships,class_name:"Relationship",foreign_key:"follower_id",dependent: :destroy
  has_many:followings,through: :relationships,source: :followed

  has_many:reverse_relationships,class_name:"Relationship",foreign_key:"followed_id",dependent: :destroy
  has_many:followers,through: :reverse_relationships,source: :follower


  has_one_attached:profile_image

  validates:name,{presence:true,uniqueness:true,length:{minimum:2,maximum:20}}
  validates:introduction,length:{maximum:50}

  def get_profile_image
    unless profile_image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[100,100]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content,method)
    if method=="perfect"
      User.where(name:content)
    elsif method=="forward"
      User.where('name LIKE?',content+'%')
    elsif method=="backward"
      User.where('name LIKE?','%'+content)
    else
      User.where('name LIKE?','%'+content+'%')
    end
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to:user
  belongs_to:room

end

app/models/view_count.rb
class ViewCount < ApplicationRecord

  belongs_to:user
  belongs_to:book

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if error.errors.any? %>
  <h3><%= error.errors.count %> error prohibited this obj from being saved:</h3>
  <ul>
    <% error.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count,"error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_search.html.erb
<div class="search_form">
  <%= form_with url:search_path,method: :get,local:true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model,options_for_select({"User"=>"user","Book"=>"book"}) %>
    <%= f.select :method,options_for_select({"完全一致"=>"perfect","前方一致"=>"forward","後方一致"=>"backward","部分一致"=>"partial",}) %>
    <%= f.submit "検索" %>
  <% end %>
</div>

app/views/layouts/_tag-search.html.erb
<div class="search_form">
  <%= form_with url:search_book_path,method: :get do |f| %>
    <%= f.text_field :keyword, value: @keyword %>
    <%= f.submit "タグ検索" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers22</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler"
                  type="button"
                  data-toggle="collapse"
                  data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id),class:"nav-link text-light" do %>
                    <i class="fas fa-home"></i>
                    Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path,class:"nav-link text-light" do %>
                    <i class="fas fa-users"></i>
                    Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path,class:"nav-link text-light" do %>
                    <i class="fas fa-book-open"></i>
                    Books
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path,method: :delete,class:"nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt"></i>
                    Log out
                  <% end %>
                </li>
                <% else %>
                <li class="nav-item">
                  <%= link_to root_path,class:"nav-link text-light" do %>
                    <i class="fas fa-home"></i>
                    Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to about_path,class:"nav-link text-light" do %>
                    <i class="fas fa-link"></i>
                    About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path,class:"nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i>
                    Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path,class:"nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i>
                    Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <diV class="row">
        <div class= "mx-auto mt-1">
          <% if user_signed_in? %>
            <%= render 'layouts/search' %>
            <%= render 'layouts/tag-search' %>
          <% end %>
        </div>
      </div>
      <p class="notice"><%= notice %></p>
      <%= yield %>
    </main>
    <footer class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>